config/routes.rb
Rails.application.routes.draw do
  resources :contents
  resources :courses
  resources :users
  
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	  has_and_belongs_to_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
	has_and_belongs_to_many :users
  has_and_belongs_to_many :contents
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true

	#A regular Expression for email validation.
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,presence: true, length: { maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
		
	 
	 has_secure_password
	 validates :password, presence: true, length: {minimum: 4}
	 
	has_and_belongs_to_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:name)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to users_url
  	else
  		flash.now[:danger] = 'Invalid credentials.'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:role)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>


<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>
<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

<% end %>


<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the Courses Index for Lecturer!" %></p>
  <h1>Contents</h1>
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the Courses Index for Student!" %></p>
    <h1>Contents</h1>
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td><%= link_to 'Show', content %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @content.name %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/courses/_course.html.erb
 
<p>Courses Name: <%= course.name %> </p>

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

<% end %>


<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the Courses Editing for Lecturer!" %></p>
  <h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

<% end %>

<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the Courses Editing for Student!" %></p>
  <P><%= "So there is nothing here. T_T & LOL" %></P>
  
<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

<% end %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>
  <h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>
<% end %>


<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the Courses Index for Lecturer!" %></p>
  <h1>Courses</h1>

  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br>
<%= link_to 'New Course', new_course_path %>
  
<% end %>
 

 
<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the Courses Index for Student!" %></p>
  <h1>Courses</h1>

  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/courses/new.html.erb
<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>
  <br>

<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>
<br>
<% end %>


<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the Courses Create page for Lecturer!" %></p>
    <br>

    <h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>
<br>

<% end %>


<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the Courses Create page for Student!" %></p>
  <P><%= "So there is nothing here. T_T & LOL" %></P>
  <br>
  <%= link_to 'Back', courses_path %>
<br>

<% end %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>



<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>
  <br>
  <p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>
<br>
<% end %>

<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the Courses Show page for Lecturer!" %></p>
    <br>
    <p>
  <strong>Name:</strong>
  <%= @course.name %>
	</p>
	<%= link_to 'Edit', edit_course_path(@course) %> |
	<%= link_to 'Back', courses_path %>
	<br>
<% end %>


<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the Courses Show page for Student!" %></p>
  <br>
  <p>
   
  <strong>Name:</strong>
  <%= @course.name %>
  </p>


	<%= link_to 'Back', courses_path %>
	<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S9@AuthenticationSample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
    <h1>Welcome, <%= current_user.name %>!</h1>
    <p>
    <% if current_user.role == "admin" %>
  		<%= yield :admin %>
  	
  	<% elsif  current_user.role.downcase == "student" %>
  		<%= yield :student %>
  	      
  	<% elsif current_user.role.downcase.include? "lecturer" %>
  		<%= yield :lecturer %>
  	<% end %>
    </p>

    <%= link_to "Log out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "log in", login_path %>
    <% end %>



    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_formfornonadmin.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

<br>


<% end %>

<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the User Edit Page for Lecturer!" %></p>
  <P><%= "So there is nothing here. T_T & LOL" %></P>

  <h1>Editing Yourself's Info </h1>

<%= render 'formfornonadmin', user: current_user %>

<%= link_to 'Show', current_user %> |
 
  <%= link_to 'Back-tobefix', users_path %>
<% end %>

<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the User Edit Page for Student!" %></p>
  <P><%= "So there is nothing here. T_T & LOL" %></P>

<h1>Editing Yourself's Info </h1>

<%= render 'formfornonadmin', user: current_user %>

<p><%= "Or Call the Admin. --To be fixed" %></p>
<%= link_to 'Show', current_user %> |
 
<%= link_to 'Back-tobefix', users_path %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for :admin do %>
  <%= "Fake news:  You are an Admin!" %>

<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

<br>


<% end %>

<% content_for :lecturer do %>
  <P><%= "Fake news:  You are an Lecturer!" %></P>
  <p><%= "Fake news:  This is the User Create Page for Lecturer!" %></p>
  <P><%= "So there is nothing here. T_T & LOL" %></P>
  <%= link_to 'Back-tobefix', users_path %>
<% end %>

<% content_for :student do %>
  <p><%= "Fake news:  You are an Student!" %></p>
  <p><%= "Fake news:  This is the User Create Page for Student!" %></p>
  <P><%= "So there is nothing here. T_T & LOL" %></P>
  <%= link_to 'Back-tobefix', users_path %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
 
<h1>Hello, Rails!-- from Welcome#index</h1>